# Site settings
title: Lenka Janosova
email: janosova.lenka@gmail.com
description: Girl power in iOS development 🌸💪.
baseurl: "/fractal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: ""

# Social settings
github_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/lenkajanosova/

# Build settings
markdown: kramdown
